/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fatalitygame;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author vchin
 */
public class Configuracion extends javax.swing.JFrame {
    private int cont = 0;
    /**
     * Creates new form Configuracion
     */
    public Configuracion() throws IOException, FontFormatException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        imagentxt = new javax.swing.JTextField();
        lblTitulo16 = new javax.swing.JLabel();
        fuegobtn = new javax.swing.JButton();
        hierrobtn = new javax.swing.JButton();
        airebtn = new javax.swing.JButton();
        aguabtn = new javax.swing.JButton();
        magiabbtn = new javax.swing.JButton();
        magianbtn = new javax.swing.JButton();
        electricidadbtn = new javax.swing.JButton();
        hielobtn = new javax.swing.JButton();
        acidbtn = new javax.swing.JButton();
        espiritualidadbtn = new javax.swing.JButton();
        fuegobtn1 = new javax.swing.JButton();
        nombretxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        titulo1.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 48)); // NOI18N
        titulo1.setForeground(new java.awt.Color(208, 0, 0));
        titulo1.setText("Choose your fighters");
        jPanel1.add(titulo1);
        titulo1.setBounds(10, 20, 510, 80);

        imagentxt.setBackground(new java.awt.Color(51, 51, 51));
        imagentxt.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        imagentxt.setForeground(new java.awt.Color(185, 185, 185));
        imagentxt.setText("Imagen");
        imagentxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagentxtActionPerformed(evt);
            }
        });
        jPanel1.add(imagentxt);
        imagentxt.setBounds(230, 120, 200, 40);

        lblTitulo16.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo16.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        lblTitulo16.setForeground(new java.awt.Color(244, 140, 6));
        lblTitulo16.setText("Armas");
        jPanel1.add(lblTitulo16);
        lblTitulo16.setBounds(20, 170, 80, 40);

        fuegobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fire.png"))); // NOI18N
        jPanel1.add(fuegobtn);
        fuegobtn.setBounds(20, 210, 90, 90);

        hierrobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iron.jpeg"))); // NOI18N
        hierrobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hierrobtnActionPerformed(evt);
            }
        });
        jPanel1.add(hierrobtn);
        hierrobtn.setBounds(420, 320, 90, 90);

        airebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/air.jpg"))); // NOI18N
        jPanel1.add(airebtn);
        airebtn.setBounds(120, 210, 90, 90);

        aguabtn.setBackground(new java.awt.Color(255, 255, 255));
        aguabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/water.png"))); // NOI18N
        jPanel1.add(aguabtn);
        aguabtn.setBounds(220, 210, 90, 90);

        magiabbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/whitemagic.jpg"))); // NOI18N
        jPanel1.add(magiabbtn);
        magiabbtn.setBounds(320, 210, 90, 90);

        magianbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blackmagic.jpg"))); // NOI18N
        jPanel1.add(magianbtn);
        magianbtn.setBounds(420, 210, 90, 90);

        electricidadbtn.setBackground(new java.awt.Color(255, 255, 255));
        electricidadbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/electricity.jpg"))); // NOI18N
        jPanel1.add(electricidadbtn);
        electricidadbtn.setBounds(20, 320, 90, 90);

        hielobtn.setBackground(new java.awt.Color(255, 255, 255));
        hielobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ice.png"))); // NOI18N
        jPanel1.add(hielobtn);
        hielobtn.setBounds(120, 320, 90, 90);

        acidbtn.setBackground(new java.awt.Color(255, 255, 255));
        acidbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/acid.jpg"))); // NOI18N
        jPanel1.add(acidbtn);
        acidbtn.setBounds(220, 320, 90, 90);

        espiritualidadbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/spirit.jpg"))); // NOI18N
        jPanel1.add(espiritualidadbtn);
        espiritualidadbtn.setBounds(320, 320, 90, 90);

        fuegobtn1.setBackground(new java.awt.Color(232, 93, 4));
        fuegobtn1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        fuegobtn1.setForeground(new java.awt.Color(0, 0, 0));
        fuegobtn1.setText("Crear");
        fuegobtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuegobtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(fuegobtn1);
        fuegobtn1.setBounds(20, 430, 160, 40);

        nombretxt.setBackground(new java.awt.Color(51, 51, 51));
        nombretxt.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        nombretxt.setForeground(new java.awt.Color(185, 185, 185));
        nombretxt.setText("Nombre");
        nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxtActionPerformed(evt);
            }
        });
        jPanel1.add(nombretxt);
        nombretxt.setBounds(20, 120, 200, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoMK2.gif"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 110, 740, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imagentxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagentxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imagentxtActionPerformed

    private void nombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretxtActionPerformed

    private void hierrobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hierrobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hierrobtnActionPerformed

    private void fuegobtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuegobtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuegobtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Configuracion().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Configuracion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (FontFormatException ex) {
                    Logger.getLogger(Configuracion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acidbtn;
    private javax.swing.JButton aguabtn;
    private javax.swing.JButton airebtn;
    private javax.swing.JButton electricidadbtn;
    private javax.swing.JButton espiritualidadbtn;
    private javax.swing.JButton fuegobtn;
    private javax.swing.JButton fuegobtn1;
    private javax.swing.JButton hielobtn;
    private javax.swing.JButton hierrobtn;
    private javax.swing.JTextField imagentxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo16;
    private javax.swing.JButton magiabbtn;
    private javax.swing.JButton magianbtn;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
